### ISSUE TITLE
[BUG] Exporting Posters and Art not working

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#382] opened 2021-06-01 05:02 UTC
Created custom profile, type = Movies, containing the Export Posters and Export Art fields only.

No output results from this at all.

**Comment by ukdtom** [comment] 2021-06-01 09:40
Is this a valid use case?

Exporting posters and arts without any other fields, like at least title?

**Comment by Clasius** [comment] 2021-06-05 02:05
I've been unable to export Art or Posters.  Export works otherwise, just errors if I add "Export Art" or "Export Posters" fields into the custom export.

![image](https://user-images.githubusercontent.com/28607009/120876768-0d97e700-c570-11eb-9301-5299ec3d812c.png)

**Comment by ukdtom** [comment] 2021-06-05 08:18
@Clasius I can't use a screen dump to anything.
I need logs in verbose mode

**Comment by Clasius** [comment] 2021-06-06 02:20
Here ya go.

[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/6603525/WebTools-NG.log)

Ended the task after the 5th or so movie gave the ENOENT error.

**Comment by ukdtom** [comment] 2021-06-06 08:39
Darn, I forgot to put in logging for this :(

See: #384 

I'll look into this, and provide a build asap

**Comment by ukdtom** [comment] 2021-06-06 13:57
Strange, but only windows build is impacted with this

**Comment by ukdtom** [comment] 2021-06-06 21:50
Darn.....

Looks like the ***** character is invalid in a filename on Windows :dancers:

**Comment by ukdtom** [comment] 2021-06-06 22:02
Windows fix will be in the next release

@trumpy81 

Can you add to known issues, that exporting posters and arts req. at least one other field?

**Comment by ukdtom** [comment] 2021-06-06 22:36
And released, so please confirm it's working now

And FYI, replaced * character with x

**Comment by trumpy81** [comment] 2021-06-06 22:47
Thanks Tommy. I will add a note on the Wiki just as soon as I have had time to test etc...

FYI, I did try it with other fields, but it did not work, so I thought it may have been because I was using other fields, so I removed them and it still did not work ... lol

**Comment by Clasius** [comment] 2021-06-07 02:16
First of all, thanks for looking into this so quickly, impressive turn-around!

I know this issue is now closed, but I did try the new build on windows and wanted to give an update.

On my library of ~1640 Movies, 4 of them appeared to have issues with file naming the poster files.  Each of the problematic titles have either a '/' in their title or a '?' (both not valid characters for windows file names).  I know screen dumps aren't ideal, but might shed some light on the problem.  The text under each image is the title as it appears in the Plex db.

Also, not sure if it's intended, but the poster files also don't have a file extension.  About ~250 of the posters don't appear to have correctly exported, having a 0 KB size.  I appended a .jpg to every other poster file with a script and can confirm the rest show up properly.

Keep up the good work, and I hope the info is useful.

![1](https://user-images.githubusercontent.com/28607009/120949347-8c705980-c701-11eb-8052-99f4b9db5dbd.png)
"50/50"

![2](https://user-images.githubusercontent.com/28607009/120949418-b45fbd00-c701-11eb-8e17-9dbc32e8e708.png)
"Frost/Nixon"

![3](https://user-images.githubusercontent.com/28607009/120949532-f983ef00-c701-11eb-841d-55abda0a529c.png)
"Superman/Batman: Apocalypse"

![4](https://user-images.githubusercontent.com/28607009/120949585-13253680-c702-11eb-8ea8-d81b9171f3c3.png)
"Thrive: What on Earth Will It Take?"

**Comment by Clasius** [comment] 2021-06-07 03:26
Line [1241](https://github.com/WebTools-NG/WebTools-NG/blob/4ca09477718aeb7155b841adc8cd0074731ff54a/src/components/modules/ExportTools/scripts/et.js#L1241) - Something like?

```js
const fileName = key + '_' + title.replace(/[/\\?%*:|"<>]/g, '-') + '_' + res.trim().replace("*", "x") + '.jpg';
```

**Comment by ukdtom** [comment] 2021-06-07 08:30
Heh, and you are 100% correct here @Clasius 

I was solely focused on the darn * character, that I forgot about others, that might cause an issue.

Wanna make a PR for this, or should I simply steal your code snip?

**Comment by Clasius** [comment] 2021-06-07 09:53
Steal away! Thanks again :)

**Comment by ukdtom** [comment] 2021-06-07 20:37
Please both try this build:

https://www.dropbox.com/s/5f19ucwqoeefk32/WebTools-NG-0.3.12.0b65312.exe?dl=0

**Comment by trumpy81** [comment] 2021-06-07 20:45
Thanks Tommy, but it's still not working for me, it gets stuck on the first image and never advances past that.

Here are the logs if it helps.
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/6611922/WebTools-NG.zip)

.

**Comment by ukdtom** [comment] 2021-06-07 21:02
@trumpy81 

Syntax is not '1920x1080' but '1920*1080'

Notice star instead of x

**Comment by trumpy81** [comment] 2021-06-07 21:08
And ..... That was it ... it is working now :)

I will have to make a note of that on the Wiki.

Thanks Tommy!

**Comment by ukdtom** [comment] 2021-06-07 21:13
Added a bit more verbose logging, in order to spot this in the future more easy

**Comment by ukdtom** [comment] 2021-06-07 23:01
@Clasius 

Regarding the 0 file size exports, can you check if they actually have valid posters and/or arts ?

Since sadly can't reproduce that part

And fixed missing extention as well ;)

**Comment by ukdtom** [comment] 2021-06-07 23:08
And forgot....

If posters/arts are not valid, then please don't fix running a refresh nor analyse on the items....

Since if so, I need to track it and then make the export file name has something like: "FIX THIS RUNNING Bla...bla..bla-Titile.NoExt"

**Comment by Clasius** [comment] 2021-06-07 23:20
I'll check it when I get home shortly... Won't attempt to refresh metadata or anything in the meantime.  That being said I did complete a full metadata refresh maybe a few weeks ago after migrating to a new Nas.  All items have posters applied in Plex.

**Comment by Clasius** [comment] 2021-06-08 01:08
Some good news, and new screenshots :)

Using the new build the poster export appears to properly be creating the image files now (all of them but one! yay, no more 0KB images).  I suspect since these images were being overwritten in the same directory with the same file name it's possible something was preventing them from overwriting properly during subsequent runs prior to the file extension being added?

Ok, so ONE poster isn't properly exporting.  I've run the export 4 times and get the following screen dumps below ([logs here](https://github.com/WebTools-NG/WebTools-NG/files/6612779/WebTools-NG_Logs.zip)).  I suspect this is possibly just something wrong with the specific image for this movie, but I will wait for your go ahead to change it and confirm.

![new1](https://user-images.githubusercontent.com/28607009/121104900-36aeb680-c7c0-11eb-8a71-23b019f1ee91.png)
The image that is produced oddly has different permissions than the rest.

```posh
PS C:\Users\MyUser> $brokenFile = "Z:\Logs\WebTools-NG\ExportTools\Posters\12729_When the Lights Went Out_75x75.jpg"

PS C:\Users\MyUser> Get-Acl $brokenFile
Get-Acl : Access is denied
At line:1 char:1
+ Get-Acl $brokenFile
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Z:\Logs\WebTool...t Out_75x75.jpg:String) [Get-Acl], UnauthorizedAccessException
    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetAclCommand
 
Get-Acl : Cannot find path 'Z:\Logs\WebTools-NG\ExportTools\Posters\12729_When the Lights Went Out_75x75.jpg' because it does not exist.
At line:1 char:1
+ Get-Acl $brokenFile
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException
    + FullyQualifiedErrorId : GetAcl_PathNotFound_Exception,Microsoft.PowerShell.Commands.GetAclCommand
```

![new2](https://user-images.githubusercontent.com/28607009/121104918-3f9f8800-c7c0-11eb-8f12-96db6520bb5e.png)
Viewing the details of the image side-by-side a fully working image.

Even without Read permissions the file does open in the default photo viewer for Win 10, but since I can't read the dimensions, or they aren't applied it is "exploded" and rather distorted.  Like viewing a 75x75 image at 300x300.

![new3](https://user-images.githubusercontent.com/28607009/121105780-fe0fdc80-c7c1-11eb-84c4-c1bb9345e9c4.png)

Side note, appears to be running much faster now... Elapsed time for 1639 Movies is ~1:30.

[WebTools-NG_Logs.zip](https://github.com/WebTools-NG/WebTools-NG/files/6612779/WebTools-NG_Logs.zip)

**Comment by Clasius** [comment] 2021-06-08 01:11
Oh yeah, could be listed as another issue I suppose, but the log files don't have an extension by default.  I've been adding .log to them.

**Comment by ukdtom** [comment] 2021-06-08 07:58
Ohh @Clasius 

What happens, if you from a browser runs above url, and in the end adds `&X-Plex-Token=XxXYyYZzZ` and for token use: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by ukdtom** [comment] 2021-06-08 22:02
@Clasius See: #388

**Comment by Clasius** [comment] 2021-06-09 00:12
Looks like directly hitting the transcode URL for that item works no problem.  Appear to be able to save the image from the browser fine with proper security on the file.

![image](https://user-images.githubusercontent.com/28607009/121273218-f5cca580-c884-11eb-8340-6ee5a1360260.png)

**Comment by Clasius** [comment] 2021-06-09 00:14
> Also, since extracting pics is a transcode process, is there anything in the PMS log itself?

I checked the PMS log this morning before work and that specific item has the same transcode lines as the other items surrounding it.

**Comment by ukdtom** [comment] 2021-06-09 00:21
Then sadly clueless for that one, and will release what I got so far

And indeed strange!

**Closed** 2021-06-09 00:38 UTC
Labels: Module-ExportTools, Priority-Blocker, bug

**Comment by Clasius** [comment] 2021-06-09 13:43
> Then sadly clueless for that one, and will release what I got so far
> 
> And indeed strange!

Ended up Moving that specific movie out of Plex library, scanning Movies, and then moving it back and re-scanning.  Passes by that movie with no issues now.  Has a new id and added date now, but no issues exporting the poster now.

Thanks for your quick responses @ukdtom!
